In [2]:
#QUESTION 1
#create a class employee
class Employee:
    #create a datamember to count the no.of employees
    no_of_employees = 0

    #create a constructor to initialize name,family,salary,department
    def __init__(self, name, family_name, salary, department):
        self.__name = name
        self.__family_name = family_name
        self.salary = salary
        self.__department = department
        Employee.no_of_employees += 1


    #create a function to average salary
    def average_salary(employees):
        sum = 0
        for employee in employees:
            sum += employee.salary
        return sum / Employee.no_of_employees
    

#create a fulltime emlpoyee class and it should inherit the properties of Employee class
class FulltimeEmployee(Employee) :

    def __init__(self, name, family_name, salary, department):
        super().__init__(name, family_name, salary, department)

    def full_time_benefits(self):
        print("full time employee Benefits.")
    

#create the instances of Fulltime Employee class and employee class and call their member functions
def main():
    employees = []
    fte1 = FulltimeEmployee("Hemanth", "1", 400000, "CSE")
    fte1.full_time_benefits()
    employees.append(fte1)
    fte2 = FulltimeEmployee("Rushitha", "2", 100000, "CIS")
    employees.append(fte2)
    emp1 = Employee("Pratysha", "3", 280000, "IT")
    employees.append(emp1)
    emp2 = Employee("Lahari", "4", 304000, "BD")
    employees.append(emp2)
    print("Average salary:", FulltimeEmployee.average_salary(employees))


if __name__ == "__main__":
    main()

full time employee Benefits.
Average salary: 271000.0


In [5]:
#QUESTION2 
#create a randomm vector of size 20 having only float in the range 1-20
import numpy as np
x=np.random.uniform(1,20,20)
print("Original array:")
print(x)
#reshape the array to 4 by 5
x1=x.reshape(4,5)
print("Reshaped Array: ")
print(x1)
#replace the max in each row by 0
x1[np.arange(len(x1)), x1.argmax(1)]=0
print("Maximum value replaced by 0:")
print(x1)

Original array:
[ 9.78347585  5.74829699 18.23498875 17.3129872  15.08046046 14.77250664
  9.15419175  3.96485954 16.59762124 17.74552834 16.4086825  14.61688349
 16.62991304 15.28975513  7.04263708  4.86311433 11.18978889 10.02438468
 14.14465394 11.51920783]
Reshaped Array: 
[[ 9.78347585  5.74829699 18.23498875 17.3129872  15.08046046]
 [14.77250664  9.15419175  3.96485954 16.59762124 17.74552834]
 [16.4086825  14.61688349 16.62991304 15.28975513  7.04263708]
 [ 4.86311433 11.18978889 10.02438468 14.14465394 11.51920783]]
Maximum value replaced by 0:
[[ 9.78347585  5.74829699  0.         17.3129872  15.08046046]
 [14.77250664  9.15419175  3.96485954 16.59762124  0.        ]
 [16.4086825  14.61688349  0.         15.28975513  7.04263708]
 [ 4.86311433 11.18978889 10.02438468  0.         11.51920783]]
